### PR TITLE
Fix cards missing error when card name is different between badge page and trade offer page

### PR DESCRIPTION
**Pull request by ngoclong19**
There are cases where the error "cards missing" is incorrectly reported.

Let's consider this check:
https://github.com/Rudokhvist/ASF-STM/blob/1fe1a276c30931bd0a9871b34d6f6c0d095b8063/ASF-STM.user.js#L1638

The card "Soldiers" has different name in badge page and trade offer/market listing page.
In badge page, it is "Soldiers":
`https://steamcommunity.com/my/gamecards/368770`
In trade offer/market listing page, it is "Soldiers (Trading Card)", the "Trading Card" part is localizable, follows user's Steam language setting:
`https://steamcommunity.com/market/listings/753/368770-Soldiers (Trading Card)`
The check `elem.name === inv[item].name` will fail.

In badge page, the card image source is:
`https://community.cloudflare.steamstatic.com/economy/image/IzMF03bk9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdA3g5gMEPvUZZEfSMJ6dESN8p_2SVTY7V2NoJzHQLmChCIzb02CleauloMc7U00PyrOOKGSmhO2CQKnTYTgk_H7pePGGM_jql7LvAQzDLQO0tFggCeqQH-mxLOJ_bIUh9g5FZpHe8klZCFxspdcAbI1m5ky1EMrwmkXJFfZkEnXX5IJzRggw2bxdpXbGyUrSWboiswS4lCQQnQfcMIoaXmwJLvOk`
In trade offer/market listing page, the card image source is:
`https://community.cloudflare.steamstatic.com/economy/image/IzMF03bk9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdA3g5gMEPvUZZEfSfIKVcT80svHaAG4bBlYBbyXAKkDkBemTs1GBhYLhfN8fCyQDpsqSEEXXwbWqSfHaNGQtpT7RZZ2HZ9zrw5eSUS26dQOAuQgwFKKMC9WJKNcGLOkRvyt1LrCO6mFZ5GwQXe8hHdwrmmSIRaORyyyARfJhVkSamIsXQg1dqbxU-XenkUbWXa4nxkSYtDBtmS75aOtyD_ijuDxRWYOY`
The check `inv[item].icon_url.endsWith(elem.hash)` will also fail.

A test trade offer URL:
`https://steamcommunity.com/tradeoffer/new/?partner=130444359&token=lvQ2oje0&source=asfstm&them=irV5Q.552990-Roma&you=JLvOk.368770-Soldiers`
It should alert "Not 1:1 trade", instead of "Cards missing".

---

In this PR, I would like to add the following changes:
- Fix cards missing error
- Format document with Prettier
- Add some type annotations
- Use `SteamIDText` from ASF bots listing API instead of `SteamID`.

Tested in Firefox 116, and Tampermonkey 4.19.

### CODE REVIEW

**Comment by Rudokhvist** [comment]
Sorry for slow response, I don't have much time for development recently, and I needed to check a few things in regards to this issue. So, that's what I have to say about it:
- Having multiple changes (prettier, type annotations and actual fix) in one PR is not convenient - this way I have to either accept all or decline all, which is not what I would like to do in this case.
- Prettier formatting is really nice, I would gladly merge it. I actually think that I need to make a github action to apply it automatically, to avoid need of such PRs. Sadly, I don't have time for that now.
- I don't understand the reason behind those type declaration. What are they for? What is a benefit of having them?
- And, at last, about the issue itself. Sadly, proposed fix is not panacea, and script can still fail with it. Having "(Trading card)" is not the only possible difference in card name, that's actually the reason why I added finding by card image hash as a second way. Here, look at this brilliant example of consistency in Steam:
image
image
Obviously, finding by market hash name will also fail for this case. And speaking of consistency - do you want to know why finding by card image fails? Apart from localized card name, steam also have possibility for localized card images. And it seems for this particular game developer bothered to upload images for all available languages... exactly same images. At first I was still surprised that script failed, since we use same language for matching and for trade offer, so we should match same image hashes, right? RIGHT? Hell no, wrong, it seems that steam ALWAYS uses ENGLISH images on badge page, but returns localized ones when polling inventory...
With all of the above in mind, I haven't decided yet how best to solve this issue. I probably can change logic for trade offers to always load inventory in English, this way finding cards by image hashes in theory _SHOULD_ always work. But I'm not that sure now that it will actually be enough, and side effect of it will be that cards in such trades will have English names, which is not convenient for the user, and on top of it I may have to load user's inventory twice this way, and that's bad in terms of rate limits. So I'm still thinking of some better way to handle it. Apart from that - I'm not even sure if I should leave finding by card name at all, with so many issues around it.

**Comment by ngoclong19** [comment]
Thank you for your response and detail analysis!

Now it is clear to me that card images could be localized.
With this new information at hand, I think this PR is irrelevance.

About the type annotation.
In the past, I have had issue due to dynamic typing, which caused unintended effect.
So with type annotation, I hope that static code analysis tools, TypeScript in this case, could catch the problem, and help to verify that what code I write is what I want.

I will close this pull request.

**Comment by Rudokhvist** [comment]
> About the type annotation.
> In the past, I have had issue due to dynamic typing, which caused unintended effect.
> So with type annotation, I hope that static code analysis tools, TypeScript in this case, could catch the problem, and help to verify that what code I write is what I want.

Idea is nice, but thing is - I don't use typescript, so it will be just an additional burden in the code for end users. I wonder if it's also can be automated with github actions too - then it would actually make sense to add those declarations.

**Comment by Rudokhvist** [comment]
Hi, I've fount a workaround for the issue you've tried to address in this PR. If you are interested in helping and have cards to match - you may test new version too https://github.com/Rudokhvist/ASF-STM/pull/25
Any feedback is welcome!

**Comment by ngoclong19** [comment]
Thank you! I'll try it out when I have more duplicate cards available.

**Pull request closed without merging**
